config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :candidates
  resources :jobs

  get '/search', to: 'searches#new', as: 'search'
  get '/unsubscribe/:token', to: 'candidates#unsubscribe', as: 'unsubscribe'
  get '/remove_account/:token', to: 'candidates#destroy', as: 'remove_account'

  root to: "jobs#index"

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base

  searchkick
  paginates_per 10

  before_save :sanitize_twitter_name
  before_create :generate_token!

  scope :emailable, -> { where( receive_updates: true ) }

  def name
    "#{first_name} #{last_name}"
  end

  private

  def sanitize_twitter_name
    self.twitter_name.gsub!('@','')
  end

  def generate_token!
    self.token = SecureRandom.uuid
  end

end

app/models/job.rb
class Job < ActiveRecord::Base

  searchkick
  paginates_per 10

  LEVELS         = %w{Entry\ Level Junior Intermediate Senior PM}
  POSITION_TYPES = %W{Full\ Time Part\ Time Apprentice Intern}

  before_save :sanitize_url
  after_commit :send_emails

  default_scope { where( is_open: true ) }

  validate :title, :location, :email, :remote_potential, :experience_level, :position_type, presence: true

  def should_index?
    is_open
  end

  private

  def sanitize_url
    self.url = "http://#{self.url}" unless self.url =~ /^http/
  end

  def send_emails
    Candidate.emailable.each do |c|
      Notifier.delay.job_posted(candidate_id: c.id, job_id: self.id)
    end
  end

end

app/models/notifier.rb
class Notifier < ActionMailer::Base
  layout "email"
  helper :application
  default from: "crbjobs@gmail.com", content_type: "text/html"

  def job_posted(info)
    @job       = Job.find(info[:job_id])
    @candidate = Candidate.find(info[:candidate_id])
    mail to: @candidate.email, subject: 'New CRB Job Posted!'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < InheritedResources::Base
  has_scope :page, default: 1

  def unsubscribe
    Candidate.where(token: params[:token]).first.update_attribute(:receive_updates, false)
  end

  def destroy
    Candidate.where(token: params[:token]).first.destroy
    redirect_to root_path
  end

  private

  def permitted_params
    params.permit(candidate: [:first_name, :last_name, :email, :github_name, :twitter_name, :experience_level, :about_me, :looking_for, :receive_updates])
  end

end

app/controllers/jobs_controller.rb
class JobsController < InheritedResources::Base
  has_scope :page, default: 1

  private

  def permitted_params
    params.permit(job: [:title, :description, :is_open, :experience_level, :email, :created_at,
                        :updated_at, :description_markdown, :position_type, :location,
                        :remote_potential, :company_name, :url])
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @term       = params[:term]
    @jobs       = Job.search @term
    @candidates = Candidate.search @term
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def boolean_answer(bool)
    bool ? "Yes" : "No"
  end

end

app/views/candidates/_table.html.slim
table
  thead
    tr
      th Name
      th Experience Level
      th Github
      th Twitter

  - @candidates.each do |c|
    tr
      td= link_to c.name, candidate_path(c)
      td= c.experience_level
      td= link_to c.github_name, "http://github.com/#{c.github_name}"
      td= link_to c.twitter_name, "http://twitter.com/#{c.twitter_name}".gsub('@', '')

app/views/candidates/index.html.slim
h1 Looking to Hire?

= render "table"
= paginate @candidates

app/views/candidates/new.html.slim
h1 Looking For A Job?

= simple_form_for @candidate do |f|
  #details
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :github_name
    = f.input :twitter_name
    = f.input :experience_level, as: :select, collection: Job::LEVELS
  #description
    = f.input :about_me, input_html: {rows: 10}
    = f.input :looking_for, input_html: {rows: 10}
    p= f.input :receive_updates, default: true
    = f.submit

app/views/candidates/show.html.slim
p
  h1= @candidate.name

#details
  p
    label Email
    = mail_to @candidate.email, @candidate.email
  p
    label Experience Level
    = @candidate.experience_level
  p
    label Github
    = link_to @candidate.github_name, "http://github.com/#{@candidate.github_name}"
  p
    label Twitter
    = link_to @candidate.twitter_name, "http://twitter.com/#{@candidate.twitter_name}".gsub('@', '')

#description
  p
    label About Me
    = @candidate.about_me
  p
    label What I'm looking for
    = @candidate.looking_for

app/views/candidates/unsubscribe.html.slim
h1 Cool, unsubscribed.

= link_to "Do you want to remove your 'For Hire' listing too?", remove_account_path(token: params[:token])

app/views/jobs/_table.html.slim
table
  thead
    tr
      th Job Title
      th Company
      th Location
      th Position Type
      th Experience Level
      th Remote?
      th Posted

  - @jobs.each do |j|
    tr
      td= link_to j.title, job_path(j)
      td= link_to j.company_name, j.url
      td= j.location
      td= j.position_type
      td= j.experience_level
      td= boolean_answer(j.remote_potential)
      td= "#{distance_of_time_in_words(j.created_at, Time.now)} ago"

app/views/jobs/index.html.slim
= render "table"
= paginate @jobs

app/views/jobs/new.html.slim
h1 Post a Job

= simple_form_for @job do |f|
  #details
    = f.input :title
    = f.input :location
    = f.input :company_name
    = f.input :url, label: "Company Website"
    = f.input :email, label: "Contact Email"
    = f.input :experience_level, as: :select, collection: Job::LEVELS
    = f.input :position_type, as: :select, collection: Job::POSITION_TYPES

  #description
    = f.input :description, input_html: {rows: 25}
    p= f.input :remote_potential, as: :boolean, label: "Open to remote workers?"

    = f.submit

app/views/jobs/show.html.slim
p
  h1= @job.title

#details
  p
    label Company
    = link_to @job.company_name, @job.url
  p
    label Experience Level
    = @job.experience_level
  p
    label Still Open?
    = boolean_answer(@job.is_open)
  p
    label Position Type
    = @job.position_type
  p
    label Remote Potential?
    = boolean_answer(@job.remote_potential)
  p
    label Location
    = @job.location
  p
    label Contact
    = mail_to @job.email, @job.email

#description
  = @job.description

app/views/layouts/application.html.slim
doctype html
html
  head
    title CRB Jobs
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "//use.typekit.net/yye7dwz.js"

    javascript:
      try { Typekit.load(); } catch(e) {}

    = csrf_meta_tags


  body
    = render partial: "shared/header"

    #header
      #bigtext
        .font.crb CRB
        .font JOBS

    .container= yield

app/views/layouts/email.html.slim
doctype html
html
  head
    title CRB Jobs
    = stylesheet_link_tag 'email', media: 'all'
  body
    = yield

app/views/notifier/job_posted.html.slim
h1= link_to @job.title, job_url(@job)

#details
  p
    label Company
    = link_to @job.company_name, @job.url
  p
    label Experience Level
    = @job.experience_level
  p
    label Still Open?
    = boolean_answer(@job.is_open)
  p
    label Position Type
    = @job.position_type
  p
    label Remote Potential?
    = boolean_answer(@job.remote_potential)
  p
    label Location
    = @job.location
  p
    label Contact
    = mail_to @job.email, @job.email

#description
  = @job.description

= link_to "Unsubscribe", unsubscribe_url(token: @candidate.token)

app/views/searches/new.html.slim
- if @jobs.present? || @candidates.present?
  h1= "Looking for \"#{@term}\""

  - if @jobs.present?
    h2= "Jobs (#{@jobs.count})"
    = render "jobs/table"

  - if @candidates.present?
    h2= "Candidates (#{@candidates.count})"
    = render "candidates/table"

- else
  h1= "Sorry; nothing for \"#{@term}\""

app/views/shared/_header.html.slim
header.navigation
  .navigation-wrapper
    a.logo href="javascript:void(0)"
      img alt="" src="http://img3.wikia.nocookie.net/__cb20120813052521/battlefordreamisland/images/5/5e/Ruby_Icon.png"

    a#js-mobile-menu.navigation-menu-button href=""  MENU
    .nav
      ul#navigation-menu
        li.nav-link
          a href="http://columbusrb.com" Columbus Ruby Brigade
        li.nav-link= link_to "All Jobs", jobs_path
        li.nav-link= link_to "Post Job", new_job_path
        li.nav-link= link_to "Looking for a Job?", new_candidate_path
        li.nav-link= link_to "Looking to Hire?", candidates_path

    .navigation-tools
      .search-bar
        .search-and-submit
          input placeholder=("Enter Search") type="search" value="#{params[:term]}"
          button type="submit"
            img alt="" src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png"